version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
    command: sleep infinity
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - MINIO_ENDPOINT=minio:9000
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      - crown-network

  postgres:
    image: ankane/pgvector:v0.5.1
    environment:
      POSTGRES_USER: crown
      POSTGRES_PASSWORD: crown
      POSTGRES_DB: crown_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crown-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - crown-network

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - crown-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  crown-network:
    driver: bridge