# Base configuration for Hydra
defaults:
  - _self_

# Training configuration
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10
  gradient_clip: 1.0
  
# Model configuration  
model:
  name: "example_model"
  hidden_size: 64
  dropout: 0.1
  
# Data configuration
data:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  seed: 42
  
# Logging
logging:
  level: INFO
  wandb_project: ${oc.env:WANDB_PROJECT}
  wandb_entity: ${oc.env:WANDB_ENTITY}
  log_interval: 10
  
# Paths
paths:
  data_dir: ./data
  model_dir: ./models
  checkpoint_dir: ./checkpoints
  
# Device
device: ${oc.env:DEVICE,auto}